[auth]

[metadata]


# [storage.local]
# ## Path to the SQLite3 database.
# path: /example/path/db.sqlite

[storage.postgresql]
host = "postgresql.example.com"
port = 3434
database = "simse"
schema = "public"
username = "simse"
[storage.postgresql.password]
# path = "secrets/storage.postgresql.password"
value = "badpassword"

[notifier]
startup_check = true
[notifier.smtp]
host = "smtp.example.com"
port = 25
## Connection timeout, in seconds
timeout = 5
username = "username"
password = "password"
sender = "Notify <notify@example.com>"
subject = "Simse Notification [{title}]"
