[server]
address = "0.0.0.0"
port = 9005

[storage.postgresql]
host = "postgresql.example.com"
port = 3434
database = "simse"
schema = "public"
username = "simse"
password_value = "password"
# password_file = "path/to/password/file"

# [storage.local]
# ## Path to the SQLite3 database.
# path: /example/path/db.sqlite


[notifier]
startup_check = true

[notifier.smtp]
host = "smtp.example.com"
port = 25
timeout = 3
sender = "Notify <notify@example.com>"
subject = "[Simse] {title}"
username = "notify@example.com"
password_value = "password"
# password_file = "path/to/password/file"
