server:
  # DNS name of the server.
  #
  # This effectively equates to what is after
  # the `@` in your users' MXIDs.
  name: "example.com"

  address: 0.0.0.0
  port: 9005

  keys:
    keyfile: "/path/to/key/file"
    
    old_keys:
      - value: "soa;idfastouathjadfkjms;dlmkfaslkdf"
        expired_ts: 12345

storage:
  postgresql:
    host: "postgresql.example.com"
    port: 5432
    database: "simse"
    schema: "public"
    username: "simse"
    passfile: "/path/to/password/file"

  # local:
  #   path: /path/to/db.sqlite3

notifiers:
  startup_check: true

  host: "smtp.example.com"
  port: 25
  sender: "Notify <notify@example.com>"
  subject: "[Simse] {{title}}"
  username: "notify@example.com"
  passfile: "/path/to/password/file"
