[package]
name = "simse-config"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "*", features = ["derive"] }
versions = { version = "*", features = ["serde"] }
lettre = { version = "*", default-features = false, features = ["serde"] }
